#!/bin/bash
set -e
URL="$1"
NAME="$2"
TAG="$3"

# Place the app inside the container
ID=$(docker run -e CURL_TIMEOUT=500 -i -a stdin progrium/buildstep /bin/bash -c "git clone $1 /app")
test $(docker wait $ID) -eq 0
docker commit $ID $NAME $TAG > /dev/null

# Run the builder script and attach to view output
if [[ -z "$TAG" ]]; then
  IMAGE=$NAME
else
  IMAGE=$NAME:$TAG
fi
ID=$(docker run -e CURL_TIMEOUT=500 -d $IMAGE /build/builder)
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $NAME $TAG > /dev/null